# Generated by Django 3.0.5 on 2021-03-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(default='', max_length=5000)),
                ('category', models.CharField(default='', max_length=70)),
                ('raisedAmmount', models.CharField(default='0', max_length=100)),
                ('targetammount', models.CharField(default='0', max_length=100)),
                ('backers', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('targetDate', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
