# Generated by Django 3.0.5 on 2021-03-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_auto_20210320_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='PhotoFileName2',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='PhotoFileName3',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='comment',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='campaign',
            name='details',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='impact',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='intro',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subcategory',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='summary',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
